language: php

services:
  - postgresql

php:
  - '7.4'

env:
  global:
    - APP_ENV=test
    - DATABASE_URL=postgresql://postgres@0.0.0.0:5432/basil-worker-db?serverVersion=12&charset=utf8
    - APP_SECRET=Secret!

before_install:
  - composer self-update --2

install:
  - composer install --prefer-dist --no-suggest
  - php bin/console doctrine:database:create
  - php bin/console doctrine:migrations:migrate --no-interaction

script:
  - composer ci

cache:
  directories:
  - "$HOME/.composer/cache/files"
