language: php

services:
  - docker
  - postgresql

php:
  - '7.4'

env:
  global:
    - APP_ENV=test
    - DATABASE_URL=postgresql://postgres@0.0.0.0:5432/basil-worker-db?serverVersion=12&charset=utf8
    - APP_SECRET=Secret!
    - WORKER_COMPILER_CONTAINER_NAME=test-compiler-container
    - WORKER_COMPILER_LOCAL_SOURCE_PATH=../tests/Fixtures/basil
    - WORKER_COMPILER_LOCAL_TARGET_PATH=../tests/build/tests
    - WORKER_COMPILER_LOCAL_MANIFEST_PATH=../tests/build/manifests
    - WORKER_COMPILER_SOURCE_PATH=/app/source
    - WORKER_COMPILER_TARGET_PATH=/app/tests
    - WORKER_COMPILER_MANIFEST_PATH=/app/manifests
    - WORKER_COMPILER_EXPOSED_PORT=9000
    - WORKER_RABBITMQ_CONTAINER_NAME=rabbitmq
    - WORKER_RABBITMQ_USER=guest
    - WORKER_RABBITMQ_PASS=guest
    - WORKER_RABBITMQ_EXPOSED_PORT=9001

before_install:
  - sudo apt-get install php-amqp
  - echo "extension = amqp.so" >> ~/.phpenv/versions/$(phpenv version-name)/etc/php.ini
  - composer self-update --2

install:
  - composer install --prefer-dist --no-suggest
  - php bin/console doctrine:database:create
  - php bin/console doctrine:migrations:migrate --no-interaction

before_script:
  - docker-compose -f tests/docker-compose.yml up -d

script:
  - composer ci

cache:
  directories:
  - "$HOME/.composer/cache/files"
