imports:
    - { resource: services/integration.yaml }

services:
    _defaults:
        autowire: true
        autoconfigure: true

    App\Tests\Services\TestTestRepository:
        public: true

    App\MessageDispatcher\TimeoutCheckMessageDispatcher:
        arguments:
            $recheckPeriodInSeconds: '%job_timeout_check_period%'
            $enabled: false
